Create Test,ts
William Please create 
tests folder and place this test.ts file code in it, so I can see if it passes Circleci . My enviroment on is misconfigured may be , as I am getting error 2 below 

Generating typings for: 5 artifacts in dir: typechain-types for target: ethers-v5
Successfully generated 20 typings!
Compiled 5 Solidity files successfully
Done in 8.23s.

D:\group project encode\token-management-smart-contract-main\token-management-smart-contract-main>yarn hardhat test
yarn run v1.22.1
warning package.json: No license field
$ "D:\group project encode\token-management-smart-contract-main\token-management-smart-contract-main\node_modules\.bin\hardhat" test
An unexpected error occurred:

tests/test.ts:13:22 - error TS2304: Cannot find name 'IERC20Lib'.

13   let tokenContract: IERC20Lib;
                        ~~~~~~~~~
tests/test.ts:22:40 - error TS2339: Property 'deploy' does not exist on type 'IERC20Lib__factory'.

22     tokenContract = await tokenFactory.deploy();