Add files via upload
On your computer download code zip files then go to tests folder and open test1.ts file to uncomment lines the coded  lines 19 to 25  to without uncommented //  hook constructor getsigners . then you will get the three errors like below :-

Error in plugin solidity-coverage: TSError: ⨯ Unable to compile TypeScript:
tests/test1.ts:20:30 - error TS2339: Property 'getSigners' does not exist on type 'typeof import("D:/token-management-smart-contract-main (1)/token-management-smart-contract-main/node_modules/ethers/lib/ethers")'.

20     accounts =  await ethers.getSigners();
                                ~~~~~~~~~~
tests/test1.ts:21:39 - error TS2339: Property 'getContractFactory' does not exist on type 'typeof import("D:/token-management-smart-contract-main (1)/token-management-smart-contract-main/node_modules/ethers/lib/ethers")'.

21     const tokenFactory = await ethers.getContractFactory();
                                         ~~~~~~~~~~~~~~~~~~
tests/test1.ts:25:21 - error TS2339: Property 'getContractFactory' does not exist on type 'typeof import("D:/token-management-smart-contract-main (1)/token-management-smart-contract-main/node_modules/ethers/lib/ethers")'.

25     token =  ethers.getContractFactory("ERC20").deploy();
                       ~~~~~~~~~~~~~~~~~~